# Generated by Django 4.2 on 2023-04-19 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='report',
            name='object_id',
        ),
        migrations.AddField(
            model_name='report',
            name='culprit_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='actors.student'),
        ),
        migrations.AddField(
            model_name='report',
            name='culprit_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crimes', to='actors.teacher'),
        ),
    ]
